### 所有社区列表
GET http://localhost:8084/api/v1/community
Content-Type: application/json
Authorization:Bearer {{token}}

### 根据id查询社区详情
GET http://localhost:8084/api/v1/community/3
Content-Type: application/json
Authorization:Bearer {{token}}

### 新建帖子
POST http://localhost:8084/api/v1/post
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "title": "好好学习",
  "content": "have a choice.",
  "community_id": 2
}

### 根据id 查询帖子
GET http://localhost:8084/api/v1/post/16788541648408576
Accept: application/json
Authorization:Bearer {{token}}

###