name: "MindShare"
mode: "dev"
port: 8084
version: "v0.0.1"
start_time: "2025-01-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: 192.168.31.165
  port: 3307
  user: "root"
  password: "root123"
  dbname: "gotest"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 192.168.31.165
  port: 6381
  password: ""
  db: 6
  pool_size: 100